#include "resource_dump.h"
#include "../framework.h"
#include "../il2cpp_resolve.h"
#include "../feature.h"
#include "../../third_party/imgui/imgui.h"
#include <cstdio>
#include <cstring>

typedef void* (__fastcall* GetStringByResourceType_t)(int32_t type, void* methodInfo);

// Il2CppString layout (x64): klass@0x00, monitor@0x08, length@0x10, chars@0x14
static const int IL2CPP_STRING_LEN_OFFSET = 0x10;
static const int IL2CPP_STRING_CHARS_OFFSET = 0x14;

static int ReadIl2CppString(void* str, char* buf, int bufSize) {
    if (!str || !buf || bufSize <= 0) return 0;
    int32_t len = *(int32_t*)((uintptr_t)str + IL2CPP_STRING_LEN_OFFSET);
    if (len <= 0 || len > 4096) { buf[0] = '\0'; return 0; }
    const wchar_t* chars = (const wchar_t*)((uintptr_t)str + IL2CPP_STRING_CHARS_OFFSET);
    int result = WideCharToMultiByte(CP_UTF8, 0, chars, len, buf, bufSize - 1, NULL, NULL);
    buf[result > 0 ? result : 0] = '\0';
    return result;
}

// ============================================================
// Feature implementation
// ============================================================
static const char* DUMP_FILE = "el_native_resources.txt";

// GetAllResourceTypes returns 8-byte elements, not the int32 ResourceType[]
// its name implies, so probing the enum range is the reliable path.
static const int32_t RES_TYPE_PROBE_MAX = 1024;

ResourceTypeDumpFeature::ResourceTypeDumpFeature() {
    name = "ResourceDump";
    enabled = true;
}

void ResourceTypeDumpFeature::Init() {
    LOG("[FEATURE] ResourceDump::Init() starting");

    m_getStringByResourceType = ResolveMethodOrFallback(
        "Assembly-CSharp", "", "UserResourcesUtil", "GetStringByResourceType", 1);

    m_resolveFailed = (m_getStringByResourceType == nullptr);

    LOG("[FEATURE] ResourceDump resolve: GetStringByResourceType=%p",
        m_getStringByResourceType);

    if (m_resolveFailed)
        LOG("[FEATURE] ResourceDump FATAL: GetStringByResourceType not resolved, dump disabled");
    else
        LOG("[FEATURE] ResourceDump ready — will dump on first frame");
}

void ResourceTypeDumpFeature::OnUpdate() {
    if (m_dumped || m_resolveFailed) return;
    m_dumped = true;

    LOG("[FEATURE] ResourceDump::OnUpdate — probing enum range 0..%d", RES_TYPE_PROBE_MAX);

    GetStringByResourceType_t fnGetStr = (GetStringByResourceType_t)m_getStringByResourceType;

    FILE* dump = fopen(DUMP_FILE, "w");
    if (dump) {
        fprintf(dump, "# ResourceType dump - generated by el_native\n");
        fprintf(dump, "# Format: enum_value = string_name\n\n");
    } else {
        LOG("[FEATURE] ResourceDump: failed to open dump file %s", DUMP_FILE);
    }

    m_entryCount = 0;
    for (int32_t resType = 0; resType <= RES_TYPE_PROBE_MAX; resType++) {
        void* strObj = nullptr;
        __try {
            strObj = fnGetStr(resType, nullptr);
        } __except (EXCEPTION_EXECUTE_HANDLER) {
            LOG("[FEATURE] ResourceDump: GetStringByResourceType(%d) crashed — stopping probe", resType);
            break;
        }

        char nameBuf[256];
        if (!strObj || ReadIl2CppString(strObj, nameBuf, sizeof(nameBuf)) <= 0)
            continue;

        // Unmapped enum values echo back their own number, or "no" for 0
        char selfName[16];
        snprintf(selfName, sizeof(selfName), "%d", resType);
        if (strcmp(nameBuf, selfName) == 0)
            continue;
        if (resType != 0 && strcmp(nameBuf, "no") == 0)
            continue;

        m_entryCount++;
        LOG("[FEATURE] ResourceType[%d] = \"%s\"", resType, nameBuf);
        if (dump) fprintf(dump, "%d = %s\n", resType, nameBuf);
    }

    if (dump) {
        fclose(dump);
        LOG("[FEATURE] ResourceDump: wrote %d entries to %s", m_entryCount, DUMP_FILE);
    }

    LOG("[FEATURE] ResourceDump complete");
}

void ResourceTypeDumpFeature::OnMenu() {
    if (m_resolveFailed) {
        ImGui::TextColored(ImVec4(1,0,0,1), "ResourceDump: resolve failed");
        return;
    }
    if (m_dumped) {
        ImGui::Text("ResourceDump: %d entries -> %s", m_entryCount, DUMP_FILE);
    } else {
        ImGui::Text("ResourceDump: pending...");
    }
}

// ============================================================
// Registration
// ============================================================
static ResourceTypeDumpFeature g_resourceDump;
static int g_dumpRegistered = (RegisterFeature(&g_resourceDump), 0);
