#include "il2cpp_resolve.h"
#include "framework.h"
#include "resolve_log.h"

// Fallback table generated by Task 8 gen_method_fallback.py
#include "method_fallback.inc"

#include <string>
#include <unordered_map>
#include <cstddef>
#include <chrono>

// ============================================================
// IL2CPP export function pointer types
// ============================================================
typedef void* (*il2cpp_domain_get_t)();
typedef void* (*mono_domain_get_assemblies_iter_t)(void* domain, void** iter);
typedef void* (*il2cpp_assembly_get_image_t)(void* assembly);
typedef const char* (*il2cpp_image_get_name_t)(void* image);
typedef uint32_t (*il2cpp_image_get_class_count_t)(void* image);
typedef void* (*il2cpp_image_get_class_t)(void* image, uint32_t index);
typedef const char* (*il2cpp_class_get_name_t)(void* klass);
typedef void* (*il2cpp_class_from_name_t)(void* image, const char* ns, const char* name);
typedef void* (*il2cpp_class_get_method_from_name_t)(void* klass, const char* name, int paramCount);
typedef void* (*il2cpp_class_get_methods_t)(void* klass, void** iter);
typedef const char* (*il2cpp_method_get_name_t)(void* method);
typedef uint32_t (*il2cpp_method_get_param_count_t)(void* method);
typedef void* (*il2cpp_class_get_parent_t)(void* klass);
typedef void* (*il2cpp_class_get_fields_t)(void* klass, void** iter);
typedef const char* (*il2cpp_field_get_name_t)(void* field);
typedef int32_t (*il2cpp_field_get_offset_t)(void* field);
typedef void* (*il2cpp_array_new_t)(void* elementClass, std::size_t length);

// ============================================================
// Resolved exports + base address (one-time init)
// ============================================================
static struct {
    bool initialized;
    uintptr_t gameAssemblyBase;

    il2cpp_domain_get_t                  domain_get;
    mono_domain_get_assemblies_iter_t    assemblies_iter;
    il2cpp_assembly_get_image_t          assembly_get_image;
    il2cpp_image_get_name_t              image_get_name;
    il2cpp_image_get_class_count_t       image_get_class_count;
    il2cpp_image_get_class_t             image_get_class;
    il2cpp_class_get_name_t              class_get_name;
    il2cpp_class_from_name_t             class_from_name;
    il2cpp_class_get_method_from_name_t  class_get_method_from_name;
    il2cpp_class_get_methods_t           class_get_methods;
    il2cpp_method_get_name_t             method_get_name;
    il2cpp_method_get_param_count_t      method_get_param_count;
    il2cpp_class_get_parent_t            class_get_parent;
    il2cpp_class_get_fields_t            class_get_fields;
    il2cpp_field_get_name_t              field_get_name;
    il2cpp_field_get_offset_t            field_get_offset;
    il2cpp_array_new_t                   array_new;
} s_exports = { false, 0 };
static ULONGLONG s_lastExportAttempt = 0;

// ============================================================
// Thread-safe cache (SRW lock + unordered_map)
// ============================================================
static SRWLOCK s_cacheLock = SRWLOCK_INIT;
static std::unordered_map<std::string, void*> s_cache;

// Build a canonical cache key like "ns.class.method(argc)"
static std::string MakeKey(const char* ns, const char* cls,
                            const char* method, int argc) {
    std::string key;
    if (ns && *ns) {
        key.append(ns);
        key.append(1, '.');
    }
    key.append(cls ? cls : "");
    key.append(1, '.');
    key.append(method ? method : "");
    char buf[32];
    snprintf(buf, sizeof(buf), "(%d)", argc);
    key.append(buf);
    return key;
}

// ============================================================
// ResolveExports — one-time GetProcAddress for IL2CPP exports
// ============================================================
static void ResolveExports() {
    if (s_exports.initialized) return;
    const ULONGLONG now = GetTickCount64();
    if (s_lastExportAttempt && now - s_lastExportAttempt < 1000) return;
    s_lastExportAttempt = now;

    HMODULE hGA = GetModuleHandleA("GameAssembly.dll");
    if (!hGA) {
        LOG("[RESOLVE] GameAssembly.dll not loaded");
        return;
    }

    s_exports.gameAssemblyBase = (uintptr_t)hGA;

    s_exports.domain_get =
        (il2cpp_domain_get_t)GetProcAddress(hGA, "il2cpp_domain_get");
    if (!s_exports.domain_get)
        s_exports.domain_get = (il2cpp_domain_get_t)GetProcAddress(hGA, "mono_domain_get");

    s_exports.assemblies_iter =
        (mono_domain_get_assemblies_iter_t)GetProcAddress(hGA, "mono_domain_get_assemblies_iter");

    s_exports.assembly_get_image =
        (il2cpp_assembly_get_image_t)GetProcAddress(hGA, "il2cpp_assembly_get_image");
    if (!s_exports.assembly_get_image)
        s_exports.assembly_get_image = (il2cpp_assembly_get_image_t)GetProcAddress(hGA, "mono_assembly_get_image");

    s_exports.image_get_name =
        (il2cpp_image_get_name_t)GetProcAddress(hGA, "il2cpp_image_get_name");
    if (!s_exports.image_get_name)
        s_exports.image_get_name = (il2cpp_image_get_name_t)GetProcAddress(hGA, "mono_image_get_name");

    s_exports.image_get_class_count =
        (il2cpp_image_get_class_count_t)GetProcAddress(hGA, "il2cpp_image_get_class_count");
    s_exports.image_get_class =
        (il2cpp_image_get_class_t)GetProcAddress(hGA, "il2cpp_image_get_class");

    s_exports.class_get_name =
        (il2cpp_class_get_name_t)GetProcAddress(hGA, "il2cpp_class_get_name");
    if (!s_exports.class_get_name)
        s_exports.class_get_name = (il2cpp_class_get_name_t)GetProcAddress(hGA, "mono_class_get_name");

    s_exports.class_from_name =
        (il2cpp_class_from_name_t)GetProcAddress(hGA, "il2cpp_class_from_name");

    s_exports.class_get_method_from_name =
        (il2cpp_class_get_method_from_name_t)GetProcAddress(hGA, "il2cpp_class_get_method_from_name");

    s_exports.class_get_methods =
        (il2cpp_class_get_methods_t)GetProcAddress(hGA, "il2cpp_class_get_methods");
    if (!s_exports.class_get_methods)
        s_exports.class_get_methods = (il2cpp_class_get_methods_t)GetProcAddress(hGA, "mono_class_get_methods");

    s_exports.method_get_name =
        (il2cpp_method_get_name_t)GetProcAddress(hGA, "il2cpp_method_get_name");
    if (!s_exports.method_get_name)
        s_exports.method_get_name = (il2cpp_method_get_name_t)GetProcAddress(hGA, "mono_method_get_name");

    s_exports.method_get_param_count =
        (il2cpp_method_get_param_count_t)GetProcAddress(hGA, "il2cpp_method_get_param_count");

    s_exports.class_get_parent =
        (il2cpp_class_get_parent_t)GetProcAddress(hGA, "il2cpp_class_get_parent");
    if (!s_exports.class_get_parent)
        s_exports.class_get_parent = (il2cpp_class_get_parent_t)GetProcAddress(hGA, "mono_class_get_parent");

    s_exports.class_get_fields =
        (il2cpp_class_get_fields_t)GetProcAddress(hGA, "il2cpp_class_get_fields");

    s_exports.field_get_name =
        (il2cpp_field_get_name_t)GetProcAddress(hGA, "il2cpp_field_get_name");

    s_exports.field_get_offset =
        (il2cpp_field_get_offset_t)GetProcAddress(hGA, "il2cpp_field_get_offset");

    s_exports.array_new =
        (il2cpp_array_new_t)GetProcAddress(hGA, "il2cpp_array_new");

    s_exports.initialized = (s_exports.domain_get != nullptr) &&
                            (s_exports.assemblies_iter != nullptr) &&
                            (s_exports.assembly_get_image != nullptr) &&
                            (s_exports.class_from_name != nullptr);

    LOG("[RESOLVE] Native exports initialized=%d (domain=%p iter=%p img=%p cls=%p)",
        s_exports.initialized ? 1 : 0,
        s_exports.domain_get, s_exports.assemblies_iter,
        s_exports.assembly_get_image, s_exports.class_from_name);
}

// ============================================================
// ResolveInit — one-time export resolution (public wrapper)
// ============================================================
void ResolveInit() {
    ResolveExports();
}

// ============================================================
// ResolveMethod — walk IL2CPP API to find native method pointer
// ============================================================
void* ResolveMethod(const char* imageHint, const char* ns, const char* cls,
                    const char* method, int argc) {
    ResolveExports();

    if (!s_exports.domain_get || !s_exports.assemblies_iter ||
        !s_exports.assembly_get_image || !s_exports.class_from_name) {
        return nullptr;
    }

    void* domain = s_exports.domain_get();
    if (!domain) return nullptr;

    void* iter = nullptr;
    while (void* assembly = s_exports.assemblies_iter(domain, &iter)) {
        void* image = s_exports.assembly_get_image(assembly);
        if (!image) continue;

        if (imageHint && *imageHint && s_exports.image_get_name) {
            const char* imgName = s_exports.image_get_name(image);
            if (!imgName || (strcmp(imgName, imageHint) != 0 && strstr(imgName, imageHint) == nullptr))
                continue;
        }

        void* klass = s_exports.class_from_name(image, ns, cls);
        if (!klass) continue;

        for (void* current = klass; current;
             current = s_exports.class_get_parent ? s_exports.class_get_parent(current) : nullptr) {
            
            if (s_exports.class_get_method_from_name) {
                void* methodInfo = s_exports.class_get_method_from_name(current, method, argc);
                if (!methodInfo && argc >= 0)
                    methodInfo = s_exports.class_get_method_from_name(current, method, -1);
                if (methodInfo) {
                    void* ptr = *reinterpret_cast<void**>(methodInfo);
                    if (ptr) return ptr;
                }
            }

            if (s_exports.class_get_methods && s_exports.method_get_name) {
                void* mIter = nullptr;
                while (void* m = s_exports.class_get_methods(current, &mIter)) {
                    const char* mName = s_exports.method_get_name(m);
                    if (mName && strcmp(mName, method) == 0) {
                        if (argc >= 0 && s_exports.method_get_param_count) {
                            uint32_t pc = s_exports.method_get_param_count(m);
                            if (pc != (uint32_t)argc) continue;
                        }
                        void* ptr = *reinterpret_cast<void**>(m);
                        if (ptr) return ptr;
                    }
                }
            }
        }
    }

    return nullptr;
}

ResolvedMethod ResolveMethodInfoOrFallback(const char* imageHint,
                                           const char* ns, const char* cls,
                                           const char* method, int argc) {
    ResolveExports();
    if (s_exports.domain_get && s_exports.assemblies_iter &&
        s_exports.assembly_get_image && s_exports.class_from_name) {
        void* domain = s_exports.domain_get();
        void* iter = nullptr;
        while (domain && iter != (void*)-1) {
            void* assembly = s_exports.assemblies_iter(domain, &iter);
            if (!assembly) break;
            void* image = s_exports.assembly_get_image(assembly);
            if (!image) continue;
            if (imageHint && *imageHint && s_exports.image_get_name) {
                const char* imageName = s_exports.image_get_name(image);
                if (!imageName || (strcmp(imageName, imageHint) != 0 && strstr(imageName, imageHint) == nullptr)) continue;
            }
            for (void* current = s_exports.class_from_name(image, ns, cls); current;
                 current = s_exports.class_get_parent ? s_exports.class_get_parent(current) : nullptr) {
                if (s_exports.class_get_method_from_name) {
                    void* info = s_exports.class_get_method_from_name(current, method, argc);
                    if (!info && argc >= 0)
                        info = s_exports.class_get_method_from_name(current, method, -1);
                    if (info) {
                        void* ptr = *reinterpret_cast<void**>(info);
                        if (ptr) return {ptr, info, false};
                    }
                }
            }
        }
    }
    void* fallback = ResolveMethodOrFallback(imageHint, ns, cls, method, argc);
    return {fallback, nullptr, fallback != nullptr};
}

int32_t ResolveFieldOffset(const char* imageHint, const char* ns,
                           const char* cls, const char* field) {
    ResolveExports();
    if (!field || !*field || !s_exports.domain_get || !s_exports.assemblies_iter ||
        !s_exports.assembly_get_image || !s_exports.class_from_name ||
        !s_exports.class_get_parent || !s_exports.class_get_fields ||
        !s_exports.field_get_name || !s_exports.field_get_offset) {
        LOG("[RESOLVE] field %s.%s -> metadata traversal unavailable", cls ? cls : "?", field ? field : "?");
        return -1;
    }

    void* domain = s_exports.domain_get();
    if (!domain) return -1;
    void* iter = nullptr;
    while (void* assembly = s_exports.assemblies_iter(domain, &iter)) {
        void* image = s_exports.assembly_get_image(assembly);
        if (!image) continue;
        if (imageHint && *imageHint && s_exports.image_get_name) {
            const char* imageName = s_exports.image_get_name(image);
            if (!imageName || (strcmp(imageName, imageHint) != 0 && strstr(imageName, imageHint) == nullptr)) continue;
        }
        void* requestedClass = s_exports.class_from_name(image, ns, cls);
        // The extracted companion resolves fields by class name only. UI
        // namespaces can move between builds while the field layout remains
        // valid, so mirror that behavior when the exact namespace misses.
        if (!requestedClass && s_exports.image_get_class_count &&
            s_exports.image_get_class && s_exports.class_get_name) {
            const uint32_t classCount = s_exports.image_get_class_count(image);
            for (uint32_t ci = 0; ci < classCount; ++ci) {
                void* candidate = s_exports.image_get_class(image, ci);
                const char* candidateName = candidate ? s_exports.class_get_name(candidate) : nullptr;
                if (candidateName && strcmp(candidateName, cls) == 0) {
                    requestedClass = candidate;
                    LOG("[RESOLVE] field %s.%s namespace fallback matched %s",
                        cls, field, candidateName);
                    break;
                }
            }
        }
        for (void* current = requestedClass; current;
             current = s_exports.class_get_parent(current)) {
            void* fIter = nullptr;
            while (void* candidate = s_exports.class_get_fields(current, &fIter)) {
                const char* candidateName = s_exports.field_get_name(candidate);
                if (candidateName && strcmp(candidateName, field) == 0) {
                    const int32_t offset = s_exports.field_get_offset(candidate);
                    LOG("[RESOLVE] field %s.%s -> +0x%X", cls, field, static_cast<unsigned>(offset));
                    return offset;
                }
            }
        }
    }
    LOG("[RESOLVE] field %s.%s -> FAILED", cls ? cls : "?", field);
    return -1;
}

void* ResolveRuntimeClass(const char* imageHint, const char* ns, const char* cls) {
    ResolveExports();
    if (!s_exports.domain_get || !s_exports.assemblies_iter ||
        !s_exports.assembly_get_image || !s_exports.class_from_name ||
        !ns || !cls) return nullptr;
    void* domain = s_exports.domain_get();
    void* iter = nullptr;
    while (domain && (iter != (void*)-1)) {
        void* assembly = s_exports.assemblies_iter(domain, &iter);
        if (!assembly) break;
        void* image = s_exports.assembly_get_image(assembly);
        if (!image) continue;
        if (imageHint && *imageHint && s_exports.image_get_name) {
            const char* name = s_exports.image_get_name(image);
            if (!name || (strcmp(name, imageHint) != 0 && strstr(name, imageHint) == nullptr)) continue;
        }
        void* klass = s_exports.class_from_name(image, ns, cls);
        if (klass) return klass;
    }
    return nullptr;
}

void* AllocateIl2CppArray(void* elementClass, std::size_t length) {
    ResolveExports();
    if (!s_exports.array_new || !elementClass) return nullptr;
    return s_exports.array_new(elementClass, length);
}

// ============================================================
// ResolveMethodOrFallback — cache + API + fallback table
// ============================================================
void* ResolveMethodOrFallback(const char* imageHint, const char* ns,
                              const char* cls, const char* method, int argc) {
    std::string key = MakeKey(ns, cls, method, argc);
    std::string shortName;
    {
        // Short display name: "class.method(argc)" or "ns.class.method(argc)"
        shortName.append(cls ? cls : "");
        shortName.append(1, '.');
        shortName.append(method ? method : "");
    }

    // --- 1. Check cache (shared lock) ---
    AcquireSRWLockShared(&s_cacheLock);
    auto it = s_cache.find(key);
    if (it != s_cache.end()) {
        void* cached = it->second;
        ReleaseSRWLockShared(&s_cacheLock);
        LOG("[RESOLVE] %s → cache (ptr=%p)", shortName.c_str(), cached);
        LogResolve(shortName.c_str(), (uintptr_t)cached, RESOLVE_SOURCE_CACHE);
        return cached;
    }
    ReleaseSRWLockShared(&s_cacheLock);

    void* result = nullptr;

    // --- 2. Try IL2CPP API ---
    result = ResolveMethod(imageHint, ns, cls, method, argc);
    if (result) {
        LOG("[RESOLVE] %s → %p (API)", shortName.c_str(), result);
        LogResolve(shortName.c_str(), (uintptr_t)result, RESOLVE_SOURCE_API);
        // Insert into cache (exclusive lock)
        AcquireSRWLockExclusive(&s_cacheLock);
        s_cache[key] = result;
        ReleaseSRWLockExclusive(&s_cacheLock);
        return result;
    }

    // --- 3. Try fallback RVA table ---
    ResolveExports(); // ensure base address
    if (s_exports.gameAssemblyBase != 0) {
        for (size_t i = 0; i < g_methodFallbackCount; i++) {
            const MethodFallbackEntry& e = g_methodFallbackTable[i];
            if (strcmp(e.klass, cls) != 0) continue;
            if (strcmp(e.method, method) != 0) continue;
            if (e.argc >= 0 && e.argc != argc) continue;
            if (e.ns && ns && strcmp(e.ns, ns) != 0) continue;

            result = (void*)(s_exports.gameAssemblyBase + e.rva);
            LOG("[RESOLVE] %s → %p (fallback RVA 0x%llX)",
                shortName.c_str(), result, (uintptr_t)e.rva);
            LogResolve(shortName.c_str(), (uintptr_t)result, RESOLVE_SOURCE_FALLBACK);
            break;
        }

        if (result) {
            // Insert into cache (exclusive lock)
            AcquireSRWLockExclusive(&s_cacheLock);
            s_cache[key] = result;
            ReleaseSRWLockExclusive(&s_cacheLock);
            return result;
        }
    }

    // --- 4. Both failed ---
    LOG("[RESOLVE] %s → FAILED (API null, no fallback entry)",
        shortName.c_str());
    LogResolve(shortName.c_str(), 0, RESOLVE_SOURCE_FAIL);
    return nullptr;
}

// ============================================================
// Resolve log ring buffer — thread-safe, lock-free
// ============================================================
namespace {
    ResolveEntry s_resolveLog[RESOLVE_LOG_MAX] = {};
    long s_resolveLogIndex = 0;
    long s_resolveLogCount = 0;
}

void LogResolve(const char* name, uintptr_t ptr, int source) {
    long idx;
    {
        long next = InterlockedIncrement(&s_resolveLogIndex);
        idx = (next - 1) % RESOLVE_LOG_MAX;
    }

    ResolveEntry* e = &s_resolveLog[idx];
    strncpy_s(e->name, sizeof(e->name), name ? name : "?", _TRUNCATE);
    e->ptr = ptr;
    e->source = source;

    // Bump count (cap at max)
    InterlockedIncrement(&s_resolveLogCount);
    long c = s_resolveLogCount;
    if (c > RESOLVE_LOG_MAX)
        InterlockedCompareExchange(&s_resolveLogCount, RESOLVE_LOG_MAX, c);
}

int GetResolveLogCount() {
    long c = s_resolveLogCount;
    return c > RESOLVE_LOG_MAX ? RESOLVE_LOG_MAX : (int)c;
}

const ResolveEntry* GetResolveLogEntry(int index) {
    if (index < 0 || index >= RESOLVE_LOG_MAX)
        return nullptr;
    int count = GetResolveLogCount();
    if (index >= count)
        return nullptr;

    // No wrap: entries at [0..count-1]
    if (count < RESOLVE_LOG_MAX)
        return &s_resolveLog[index];

    // Wrapped: logical index = (rawIdx - RESOLVE_LOG_MAX + index) % RESOLVE_LOG_MAX
    long rawIdx = s_resolveLogIndex;
    int pos = (int)(rawIdx - RESOLVE_LOG_MAX + index) % RESOLVE_LOG_MAX;
    if (pos < 0) pos += RESOLVE_LOG_MAX;
    return &s_resolveLog[pos];
}
