#include "il2cpp_resolve.h"
#include "framework.h"
#include "resolve_log.h"

// Fallback table generated by Task 8 gen_method_fallback.py
#include "method_fallback.inc"

#include <string>
#include <unordered_map>

// ============================================================
// IL2CPP export function pointer types
// ============================================================
typedef void* (*il2cpp_domain_get_t)();
typedef void** (*il2cpp_domain_get_assemblies_t)(void* domain, size_t* count);
typedef void* (*il2cpp_assembly_get_image_t)(void* assembly);
typedef const char* (*il2cpp_image_get_name_t)(void* image);
typedef void* (*il2cpp_class_from_name_t)(void* image, const char* ns, const char* name);
typedef void* (*il2cpp_class_get_method_from_name_t)(void* klass, const char* name, int paramCount);
typedef void* (*il2cpp_method_get_pointer_t)(void* method);

// ============================================================
// Resolved exports + base address (one-time init)
// ============================================================
static struct {
    bool initialized;
    uintptr_t gameAssemblyBase;

    il2cpp_domain_get_t             domain_get;
    il2cpp_domain_get_assemblies_t  domain_get_assemblies;
    il2cpp_assembly_get_image_t     assembly_get_image;
    il2cpp_image_get_name_t         image_get_name;
    il2cpp_class_from_name_t        class_from_name;
    il2cpp_class_get_method_from_name_t class_get_method_from_name;
    il2cpp_method_get_pointer_t     method_get_pointer;
} s_exports = { false, 0, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr };

// ============================================================
// Thread-safe cache (SRW lock + unordered_map)
// ============================================================
static SRWLOCK s_cacheLock = SRWLOCK_INIT;
static std::unordered_map<std::string, void*> s_cache;

// Build a canonical cache key like "ns.class.method(argc)"
static std::string MakeKey(const char* ns, const char* cls,
                            const char* method, int argc) {
    std::string key;
    if (ns && *ns) {
        key.append(ns);
        key.append(1, '.');
    }
    key.append(cls ? cls : "");
    key.append(1, '.');
    key.append(method ? method : "");
    char buf[32];
    snprintf(buf, sizeof(buf), "(%d)", argc);
    key.append(buf);
    return key;
}

// ============================================================
// ResolveExports — one-time GetProcAddress for IL2CPP exports
// ============================================================
static void ResolveExports() {
    if (s_exports.initialized) return;

    HMODULE hGA = GetModuleHandleA("GameAssembly.dll");
    if (!hGA) {
        LOG("[RESOLVE] GameAssembly.dll not loaded");
        return;
    }

    s_exports.gameAssemblyBase = (uintptr_t)hGA;

    s_exports.domain_get =
        (il2cpp_domain_get_t)GetProcAddress(hGA, "il2cpp_domain_get");
    s_exports.domain_get_assemblies =
        (il2cpp_domain_get_assemblies_t)GetProcAddress(hGA, "il2cpp_domain_get_assemblies");
    s_exports.assembly_get_image =
        (il2cpp_assembly_get_image_t)GetProcAddress(hGA, "il2cpp_assembly_get_image");
    s_exports.image_get_name =
        (il2cpp_image_get_name_t)GetProcAddress(hGA, "il2cpp_image_get_name");
    s_exports.class_from_name =
        (il2cpp_class_from_name_t)GetProcAddress(hGA, "il2cpp_class_from_name");
    s_exports.class_get_method_from_name =
        (il2cpp_class_get_method_from_name_t)GetProcAddress(hGA, "il2cpp_class_get_method_from_name");
    s_exports.method_get_pointer =
        (il2cpp_method_get_pointer_t)GetProcAddress(hGA, "il2cpp_method_get_pointer");

    s_exports.initialized = true;

    LOG("[RESOLVE] Exports: domain_get=%p assemblies=%p image=%p class_from_name=%p "
        "get_method=%p get_ptr=%p base=0x%llX",
        s_exports.domain_get, s_exports.domain_get_assemblies,
        s_exports.assembly_get_image, s_exports.class_from_name,
        s_exports.class_get_method_from_name, s_exports.method_get_pointer,
        s_exports.gameAssemblyBase);
}

// ============================================================
// ResolveInit — one-time export resolution (public wrapper)
// ============================================================
void ResolveInit() {
    ResolveExports();
}

// ============================================================
// ResolveMethod — walk IL2CPP API to find native method pointer
// ============================================================
void* ResolveMethod(const char* imageHint, const char* ns, const char* cls,
                    const char* method, int argc) {
    ResolveExports();

    if (!s_exports.domain_get || !s_exports.class_from_name ||
        !s_exports.class_get_method_from_name || !s_exports.method_get_pointer) {
        LOG("[RESOLVE] Missing required IL2CPP exports — cannot resolve via API");
        return nullptr;
    }

    void* domain = s_exports.domain_get();
    if (!domain) {
        LOG("[RESOLVE] il2cpp_domain_get returned null");
        return nullptr;
    }

    // Walk assemblies if we have the full traversal chain
    if (s_exports.domain_get_assemblies && s_exports.assembly_get_image) {
        size_t assemblyCount = 0;
        void** assemblies = s_exports.domain_get_assemblies(domain, &assemblyCount);
        if (!assemblies || assemblyCount == 0) {
            LOG("[RESOLVE] No assemblies found");
            return nullptr;
        }

        for (size_t i = 0; i < assemblyCount; i++) {
            void* image = s_exports.assembly_get_image(assemblies[i]);
            if (!image) continue;

            // Optional: filter by imageHint
            if (imageHint && *imageHint && s_exports.image_get_name) {
                const char* imgName = s_exports.image_get_name(image);
                if (!imgName || strcmp(imgName, imageHint) != 0) {
                    continue;
                }
            }

            void* klass = s_exports.class_from_name(image, ns, cls);
            if (!klass) continue;

            void* methodInfo = s_exports.class_get_method_from_name(klass, method, argc);
            if (!methodInfo) {
                // Try with -1 (varargs / any param count)
                if (argc >= 0)
                    methodInfo = s_exports.class_get_method_from_name(klass, method, -1);
            }
            if (!methodInfo) continue;

            void* ptr = s_exports.method_get_pointer(methodInfo);
            if (ptr) return ptr;
        }
    } else {
        // Minimal path: try corlib or first assembly
        // Without domain_get_assemblies, we can still try class_from_name
        // if the game exposes a direct path — but this is unlikely.
        LOG("[RESOLVE] Incomplete IL2CPP traversal chain — cannot walk assemblies");
    }

    return nullptr;
}

// ============================================================
// ResolveMethodOrFallback — cache + API + fallback table
// ============================================================
void* ResolveMethodOrFallback(const char* imageHint, const char* ns,
                              const char* cls, const char* method, int argc) {
    std::string key = MakeKey(ns, cls, method, argc);
    std::string shortName;
    {
        // Short display name: "class.method(argc)" or "ns.class.method(argc)"
        shortName.append(cls ? cls : "");
        shortName.append(1, '.');
        shortName.append(method ? method : "");
    }

    // --- 1. Check cache (shared lock) ---
    AcquireSRWLockShared(&s_cacheLock);
    auto it = s_cache.find(key);
    if (it != s_cache.end()) {
        void* cached = it->second;
        ReleaseSRWLockShared(&s_cacheLock);
        LOG("[RESOLVE] %s → cache (ptr=%p)", shortName.c_str(), cached);
        LogResolve(shortName.c_str(), (uintptr_t)cached, RESOLVE_SOURCE_CACHE);
        return cached;
    }
    ReleaseSRWLockShared(&s_cacheLock);

    void* result = nullptr;

    // --- 2. Try IL2CPP API ---
    result = ResolveMethod(imageHint, ns, cls, method, argc);
    if (result) {
        LOG("[RESOLVE] %s → %p (API)", shortName.c_str(), result);
        LogResolve(shortName.c_str(), (uintptr_t)result, RESOLVE_SOURCE_API);
        // Insert into cache (exclusive lock)
        AcquireSRWLockExclusive(&s_cacheLock);
        s_cache[key] = result;
        ReleaseSRWLockExclusive(&s_cacheLock);
        return result;
    }

    // --- 3. Try fallback RVA table ---
    ResolveExports(); // ensure base address
    if (s_exports.gameAssemblyBase != 0) {
        for (size_t i = 0; i < g_methodFallbackCount; i++) {
            const MethodFallbackEntry& e = g_methodFallbackTable[i];
            if (strcmp(e.klass, cls) != 0) continue;
            if (strcmp(e.method, method) != 0) continue;
            if (e.argc >= 0 && e.argc != argc) continue;
            if (e.ns && ns && strcmp(e.ns, ns) != 0) continue;

            result = (void*)(s_exports.gameAssemblyBase + e.rva);
            LOG("[RESOLVE] %s → %p (fallback RVA 0x%llX)",
                shortName.c_str(), result, (uintptr_t)e.rva);
            LogResolve(shortName.c_str(), (uintptr_t)result, RESOLVE_SOURCE_FALLBACK);
            break;
        }

        if (result) {
            // Insert into cache (exclusive lock)
            AcquireSRWLockExclusive(&s_cacheLock);
            s_cache[key] = result;
            ReleaseSRWLockExclusive(&s_cacheLock);
            return result;
        }
    }

    // --- 4. Both failed ---
    LOG("[RESOLVE] %s → FAILED (API null, no fallback entry)",
        shortName.c_str());
    LogResolve(shortName.c_str(), 0, RESOLVE_SOURCE_FAIL);
    return nullptr;
}

// ============================================================
// Resolve log ring buffer — thread-safe, lock-free
// ============================================================
namespace {
    ResolveEntry s_resolveLog[RESOLVE_LOG_MAX] = {};
    long s_resolveLogIndex = 0;
    long s_resolveLogCount = 0;
}

void LogResolve(const char* name, uintptr_t ptr, int source) {
    long idx;
    {
        long next = InterlockedIncrement(&s_resolveLogIndex);
        idx = (next - 1) % RESOLVE_LOG_MAX;
    }

    ResolveEntry* e = &s_resolveLog[idx];
    strncpy_s(e->name, sizeof(e->name), name ? name : "?", _TRUNCATE);
    e->ptr = ptr;
    e->source = source;

    // Bump count (cap at max)
    InterlockedIncrement(&s_resolveLogCount);
    long c = s_resolveLogCount;
    if (c > RESOLVE_LOG_MAX)
        InterlockedCompareExchange(&s_resolveLogCount, RESOLVE_LOG_MAX, c);
}

int GetResolveLogCount() {
    long c = s_resolveLogCount;
    return c > RESOLVE_LOG_MAX ? RESOLVE_LOG_MAX : (int)c;
}

const ResolveEntry* GetResolveLogEntry(int index) {
    if (index < 0 || index >= RESOLVE_LOG_MAX)
        return nullptr;
    int count = GetResolveLogCount();
    if (index >= count)
        return nullptr;

    // No wrap: entries at [0..count-1]
    if (count < RESOLVE_LOG_MAX)
        return &s_resolveLog[index];

    // Wrapped: logical index = (rawIdx - RESOLVE_LOG_MAX + index) % RESOLVE_LOG_MAX
    long rawIdx = s_resolveLogIndex;
    int pos = (int)(rawIdx - RESOLVE_LOG_MAX + index) % RESOLVE_LOG_MAX;
    if (pos < 0) pos += RESOLVE_LOG_MAX;
    return &s_resolveLog[pos];
}
